(() => {
  'use strict';
  const KEY = 'agent-performance-tracker-v1';
  const GH_CONFIG_KEY = 'agent-tracker-github-config-v1';
  const GH_TOKEN_KEY = 'agent-tracker-github-token-session-v1';
  let githubSync = { busy: false, timer: null, connected: false, sha: null, lastSaved: null };
  let githubSaveQueue = Promise.resolve();
  const $ = (id) => document.getElementById(id);
  const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  const uid = () => (crypto && crypto.randomUUID) ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const defaultState = () => ({ version: 1, agents: [], records: [], actions: [], audit: [], settings: { cvrTarget: 30, frtThreshold: null, ahtThreshold: null, loginTolerance: 0.25, repeatThreshold: 3 } });
  let state = loadState();
  function loadState() { try { const raw = localStorage.getItem(KEY); if (!raw) return defaultState(); const parsed = JSON.parse(raw); return { ...defaultState(), ...parsed, settings: { ...defaultState().settings, ...(parsed.settings || {}) }, agents: Array.isArray(parsed.agents)?parsed.agents:[], records:Array.isArray(parsed.records)?parsed.records:[], actions:Array.isArray(parsed.actions)?parsed.actions:[], audit:Array.isArray(parsed.audit)?parsed.audit:[] }; } catch { return defaultState(); } }
  function persist() { try { localStorage.setItem(KEY, JSON.stringify(state)); } catch { toast('Could not save. Browser storage may be full; export a backup and remove large data.'); return; } scheduleGitHubSave(); }
  function ghConfig() {
    try { return JSON.parse(localStorage.getItem(GH_CONFIG_KEY) || '{}'); } catch { return {}; }
  }
  function ghToken() { try { return sessionStorage.getItem(GH_TOKEN_KEY) || ''; } catch { return ''; } }
  function ghApiUrl(path='') {
    const c=ghConfig();
    const base=`https://api.github.com/repos/${encodeURIComponent(c.owner||'')}/${encodeURIComponent(c.repo||'')}`;
    return path ? `${base}/contents/${String(path).split('/').map(encodeURIComponent).join('/')}` : base;
  }
  function ghHeaders() { return { 'Accept':'application/vnd.github+json', 'Authorization':`Bearer ${ghToken()}`, 'X-GitHub-Api-Version':'2022-11-28', 'Content-Type':'application/json' }; }
  function ghMessage(message, error=false) {
    const el=$('github-sync-message'); if(el){el.textContent=message;el.style.color=error?'var(--red)':'var(--green)';}
    const badge=$('github-sync-badge'); if(badge){badge.textContent=githubSync.connected?(githubSync.busy?'Syncing…':'Auto-save on'):'Not connected';badge.className=`pill ${githubSync.connected?'green':'gray'}`;}
  }
  function ghValidate() {
    const owner=$('github-owner').value.trim(), repo=$('github-repo').value.trim(), branch=$('github-branch').value.trim()||'main', path=$('github-path').value.trim()||'data/agent-tracker-data.json', token=$('github-token').value.trim()||ghToken();
    if(!owner||!repo||!token) throw new Error('Enter repository owner, repository name, and a GitHub token.');
    if(path.startsWith('/')||path.split('/').includes('..')) throw new Error('Use a relative file path without .. segments.');
    localStorage.setItem(GH_CONFIG_KEY,JSON.stringify({owner,repo,branch,path}));
    try { sessionStorage.setItem(GH_TOKEN_KEY,token); } catch {}
    $('github-token').value='';
    return {owner,repo,branch,path,token};
  }
  async function ghRequest(url, options={}) {
    const res=await fetch(url,{...options,headers:{...ghHeaders(),...(options.headers||{})}});
    if(!res.ok){let detail='';try{const j=await res.json();detail=j.message||'';}catch{};if(res.status===401)throw new Error('GitHub rejected the token. Check that it is valid and has access to the private data repository.');if(res.status===403)throw new Error('GitHub denied access. Check the token permissions and repository access.');if(res.status===404)throw new Error('Repository or data file not found. Check the owner, repository, branch, and file path.');throw new Error(`GitHub API error (${res.status})${detail?': '+detail:''}`);}
    if(res.status===204)return null; return res.json();
  }
  function utf8ToBase64(str) { const bytes=new TextEncoder().encode(str); let binary=''; for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary); }
  function base64ToUtf8(b64) { const binary=atob(b64.replace(/\n/g,''));const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes); }
  async function ghGetFile() {
    const c=ghConfig();
    try { return await ghRequest(`${ghApiUrl(c.path)}?ref=${encodeURIComponent(c.branch||'main')}`); }
    catch(err) { if(String(err.message).includes('not found')) return null; throw err; }
  }
  async function ghSaveNow() {
    if(!githubSync.connected||!ghToken())return;
    if(githubSync.busy){githubSync.pending=true;return;}
    githubSync.busy=true;ghMessage('Saving latest changes to GitHub…');
    try {
      githubSaveQueue=githubSaveQueue.then(async()=>{
        const c=ghConfig();
        const current=await ghGetFile();
        const body={message:`Update agent tracker data (${today()})`,content:utf8ToBase64(JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)),branch:c.branch||'main'};
        if(current?.sha)body.sha=current.sha;
        const result=await ghRequest(ghApiUrl(c.path),{method:'PUT',body:JSON.stringify(body)});
        githubSync.sha=result?.content?.sha||null;githubSync.lastSaved=new Date();
      });
      await githubSaveQueue;
      ghMessage(`Auto-saved to GitHub at ${githubSync.lastSaved.toLocaleTimeString()}.`);
    } catch(err) { ghMessage(`Local save succeeded, but GitHub sync failed: ${err.message}`,true); }
    finally {githubSync.busy=false;if(githubSync.pending){githubSync.pending=false;scheduleGitHubSave();}}
  }
  function scheduleGitHubSave() {
    if(!githubSync.connected||!ghToken())return;
    clearTimeout(githubSync.timer);githubSync.timer=setTimeout(()=>ghSaveNow(),900);
    ghMessage('Changes saved locally; GitHub sync queued…');
  }
  async function connectGitHub(mode) {
    try {
      ghValidate();
      ghMessage('Checking GitHub access…');
      await ghRequest(ghApiUrl());
      const c=ghConfig();
      githubSync.connected=true;
      if(mode==='load'){
        const remote=await ghGetFile();
        if(!remote)throw new Error('The data file does not exist yet. Use “Connect & upload local data” to create it.');
        const parsed=JSON.parse(base64ToUtf8(remote.content||''));
        if(!parsed||!Array.isArray(parsed.agents)||!Array.isArray(parsed.records)||!Array.isArray(parsed.actions))throw new Error('The GitHub data file is not a valid tracker backup.');
        if(!confirm('Load the GitHub data into this browser? This replaces the current local tracker data. Export a backup first if needed.')){githubSync.connected=false;ghMessage('Connection cancelled. Local data was not changed.');return;}
        state={...defaultState(),...parsed,settings:{...defaultState().settings,...(parsed.settings||{})},agents:parsed.agents,records:parsed.records,actions:parsed.actions,audit:Array.isArray(parsed.audit)?parsed.audit:[]};
        localStorage.setItem(KEY,JSON.stringify(state));githubSync.sha=remote.sha||null;renderAll();loadSettingsForm();resetDailyForm();clearActionForm();
        ghMessage('Connected. GitHub data loaded; future changes will auto-save.');toast('Loaded data from GitHub');
      } else {
        const remote=await ghGetFile();
        if(remote&&!confirm('A data file already exists on GitHub. Uploading local data will replace it. Continue?')){githubSync.connected=false;ghMessage('Upload cancelled.');return;}
        await ghSaveNow();
        if(githubSync.connected)toast('GitHub auto-save enabled');
      }
      renderDashboard();
    } catch(err) {githubSync.connected=false;ghMessage(err.message||'Could not connect to GitHub.',true);}
  }
  function disconnectGitHub(){githubSync.connected=false;clearTimeout(githubSync.timer);try{sessionStorage.removeItem(GH_TOKEN_KEY);}catch{};ghMessage('Disconnected. Changes will save only in this browser until you reconnect.');}
  function initGitHubSettings(){const c=ghConfig();if($('github-owner')){$('github-owner').value=c.owner||'';$('github-repo').value=c.repo||'';$('github-branch').value=c.branch||'main';$('github-path').value=c.path||'data/agent-tracker-data.json';if(ghToken()){githubSync.connected=true;ghMessage('Token available for this tab. Auto-save is on.');}}}
  function audit(type, entityId, details) { state.audit.push({ id:uid(), timestamp:new Date().toISOString(), type, entityId, details }); if (state.audit.length > 2000) state.audit = state.audit.slice(-2000); }
  function esc(v) { return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function num(id, fallback=0) { const v = $(id).value.trim(); if (v === '') return fallback; const n = Number(v); return Number.isFinite(n) ? n : fallback; }
  function dateText(date) { if (!date) return '—'; return new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}); }
  function fmt(n, digits=1) { return Number.isFinite(Number(n)) ? Number(n).toLocaleString(undefined,{maximumFractionDigits:digits}) : '—'; }
  function agentById(id) { return state.agents.find(a=>a.id===id); }
  function initials(name='?') { return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase(); }
  function presentRecord(r) { return r && r.attendance === 'Present'; }
  function cvr(r) { return Number(r.totalChats)>0 ? Number(r.verifiedOrders)/Number(r.totalChats)*100 : null; }
  function flags(r) {
    if (!presentRecord(r)) return [];
    const f=[]; const s=state.settings;
    if (s.frtThreshold !== null && s.frtThreshold !== '' && Number(r.frtMisses) > Number(s.frtThreshold)) f.push({key:'FRT',label:'FRT',detail:`${r.frtMisses} misses`});
    const rate=cvr(r); if (rate !== null && rate < Number(s.cvrTarget)) f.push({key:'Conversion',label:'Conversion',detail:`${fmt(rate)}% vs ${fmt(s.cvrTarget)}%`});
    if (Number(r.adherenceMisses)>0) f.push({key:'Shift adherence',label:'Shift adherence',detail:`${r.adherenceMisses} miss(es)`});
    if (Number(r.requiredHours)-Number(r.actualHours) > Number(s.loginTolerance)) f.push({key:'Login hours',label:'Login hours',detail:`${fmt(Math.max(0,Number(r.requiredHours)-Number(r.actualHours)),2)}h short`});
    if (s.ahtThreshold !== null && s.ahtThreshold !== '' && r.aht !== null && r.aht !== '' && Number(r.aht)>Number(s.ahtThreshold)) f.push({key:'AHT',label:'AHT',detail:`${fmt(r.aht)} min`});
    return f;
  }
  function totalMisses(r) { return flags(r).length; }
  function badge(text, type='gray') { return `<span class="pill ${type}">${esc(text)}</span>`; }
  function statusBadge(status) { return badge(status, ({Present:'green','Weekly Off':'blue',CL:'blue',LOP:'amber'})[status] || 'gray'); }
  function empty(msg) { return `<div class="empty-state">${esc(msg)}</div>`; }
  function table(headers, rows, emptyText='No records found.') { if (!rows.length) return empty(emptyText); return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
  function agentCell(a) { return `<div class="agent-cell"><div class="avatar">${esc(initials(a?.name || 'Unknown'))}</div><div><div class="agent-name">${esc(a?.name || 'Unknown agent')}</div><div class="sub-cell">${esc(a?.employeeId || '')}</div></div></div>`; }
  function toast(message) { const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2800); }
  function setMessage(id, message, error=false) { const el=$(id); el.textContent=message; el.style.color=error?'var(--red)':'var(--green)'; }
  function csvEscape(v) { const s=String(v ?? ''); return /[",\n\r]/.test(s) ? `"${s.replace(/"/g,'""')}"` : s; }
  function download(name, content, type) { const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
  function recordsCsv(records) { const cols=['date','agentName','employeeId','attendance','frtMisses','totalChats','verifiedOrders','cvrPercent','adherenceMisses','actualHours','requiredHours','loginShortfall','ahtMinutes','flaggedCategories','notes']; const lines=[cols.join(',')]; records.forEach(r=>{ const a=agentById(r.agentId); const vals=[r.date,a?.name||'Unknown',a?.employeeId||'',r.attendance,r.frtMisses,r.totalChats,r.verifiedOrders,cvr(r)===null?'':cvr(r).toFixed(2),r.adherenceMisses,r.actualHours,r.requiredHours,Math.max(0,Number(r.requiredHours)-Number(r.actualHours)),r.aht,flags(r).map(f=>f.key).join('; '),r.notes||r.lopReason||'']; lines.push(vals.map(csvEscape).join(',')); }); return lines.join('\r\n'); }
  function fillAgentSelects() { const active=state.agents.filter(a=>a.active); const opts=active.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} (${esc(a.employeeId)})</option>`).join(''); const current=$('entry-agent').value; $('entry-agent').innerHTML=opts || '<option value="">Add an agent first</option>'; if(active.some(a=>a.id===current)) $('entry-agent').value=current; const actionCurrent=$('action-agent').value; $('action-agent').innerHTML=opts || '<option value="">Add an agent first</option>'; if(active.some(a=>a.id===actionCurrent)) $('action-agent').value=actionCurrent; const filterCurrent=$('filter-agent').value; $('filter-agent').innerHTML='<option value="">All agents</option>'+state.agents.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}${a.active?'':' (inactive)'}</option>`).join(''); $('filter-agent').value=filterCurrent; }
  function go(view) { document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`)); document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); const names={dashboard:'Dashboard',daily:'Daily entry',history:'Records & history',agents:'Agents',actions:'Coaching & actions',backup:'Backup & settings'}; $('page-title').textContent=names[view]||'Dashboard'; if(view==='dashboard') renderDashboard(); if(view==='daily') renderDateRecords(); if(view==='history') renderHistory(); if(view==='agents') renderAgents(); if(view==='actions') renderActions(); if(view==='backup') loadSettingsForm(); window.scrollTo({top:0,behavior:'smooth'}); }
  function renderDashboard() {
    const date=$('dashboard-date').value || today(); const day=state.records.filter(r=>r.date===date); const active=state.agents.filter(a=>a.active); const eligible=day.filter(presentRecord); const sumFlags=eligible.reduce((n,r)=>n+totalMisses(r),0); const frt=eligible.reduce((n,r)=>n+Number(r.frtMisses||0),0); const below=eligible.filter(r=>cvr(r)!==null&&cvr(r)<Number(state.settings.cvrTarget)).length; const adherence=eligible.reduce((n,r)=>n+Number(r.adherenceMisses||0),0); const short=eligible.filter(r=>Number(r.requiredHours)-Number(r.actualHours)>Number(state.settings.loginTolerance)).length; const ahtMiss=eligible.filter(r=>state.settings.ahtThreshold!==null&&r.aht!==null&&r.aht!==''&&Number(r.aht)>Number(state.settings.ahtThreshold)).length; const lops=day.filter(r=>r.attendance==='LOP').length; const cls=day.filter(r=>r.attendance==='CL').length; const offs=day.filter(r=>r.attendance==='Weekly Off').length; const missing=active.filter(a=>!day.some(r=>r.agentId===a.id)).length;
    const cards=[['Active agents',active.length,'Current team roster','♙'],['Performance flags',sumFlags,'Across present agents','⚑'],['FRT misses',frt,'Raw miss count','◷'],['Below CVR target',below,`Target ${fmt(state.settings.cvrTarget)}%`,'%'],['Adherence incidents',adherence,'Recorded incidents','↔'],['Login-hour misses',short,'Above tolerance','⌁'],['AHT misses',ahtMiss,state.settings.ahtThreshold===null?'Threshold not set':`Above ${fmt(state.settings.ahtThreshold)} min`,'⌛'],['Missing entries',missing,'Scheduled day without a record','!']];
    $('kpi-grid').innerHTML=cards.map((c,i)=>`<div class="kpi"><div class="kpi-top"><span>${c[0]}</span><span class="kpi-icon">${c[3]}</span></div><div class="kpi-value">${fmt(c[1],0)}</div><div class="kpi-sub">${c[2]}</div></div>`).join('');
    const categories=[['FRT',eligible.reduce((n,r)=>n+(state.settings.frtThreshold!==null&&Number(r.frtMisses)>Number(state.settings.frtThreshold)?1:0),0)],['Conversion',below],['Adherence',eligible.filter(r=>Number(r.adherenceMisses)>0).length],['Login hours',short],['AHT',ahtMiss]]; const max=Math.max(1,...categories.map(x=>x[1])); $('category-chart').innerHTML=categories.map(([name,val])=>`<div class="bar-row"><span class="bar-label">${esc(name)}</span><div class="bar-track"><div class="bar-fill" style="width:${val/max*100}%"></div></div><span class="bar-value">${val}</span></div>`).join('');
    $('attendance-summary').innerHTML=[['Present',eligible.length,'tile-green'],['Weekly Off',offs,'tile-blue'],['CL',cls,'tile-amber'],['LOP',lops,'tile-red']].map(x=>`<div class="attendance-tile ${x[2]}"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
    const ranked=eligible.map(r=>({r,a:agentById(r.agentId),f:flags(r)})).sort((x,y)=>y.f.length-x.f.length || Number(y.r.frtMisses)-Number(x.r.frtMisses)).filter(x=>x.f.length>0).slice(0,7); $('attention-table').innerHTML=table(['Agent','CVR','FRT misses','Flags','Categories'],ranked.map(({r,a,f})=>`<tr><td>${agentCell(a)}</td><td>${cvr(r)===null?'—':badge(`${fmt(cvr(r))}%`,cvr(r)<state.settings.cvrTarget?'red':'green')}</td><td>${fmt(r.frtMisses,0)}</td><td>${badge(f.length,'red')}</td><td>${f.map(x=>badge(x.label,'gray')).join(' ')}</td></tr>`),'No performance flags for this date.');
  }
  function updateMetricPreview() { const attendance=$('attendance').value; const box=$('metric-preview'); if(attendance!=='Present'){box.innerHTML='';return;} const draft={attendance,frtMisses:num('frt-misses'),totalChats:num('total-chats'),verifiedOrders:num('verified-orders'),actualHours:num('actual-hours'),requiredHours:num('required-hours'),aht:$('aht').value===''?null:num('aht'),adherenceMisses:num('adherence-count')}; const f=flags(draft); const rate=cvr(draft); const pills=[`CVR: ${rate===null?'N/A':fmt(rate)+'%'}`,`Login shortfall: ${fmt(Math.max(0,draft.requiredHours-draft.actualHours),2)}h`,...f.map(x=>`Flag: ${x.label}`)]; box.innerHTML=pills.map((p,i)=>`<span class="preview-pill ${i>1?'bad':i===0&&rate!==null&&rate<state.settings.cvrTarget?'bad':'good'}">${esc(p)}</span>`).join(''); }
  function resetDailyForm() { $('daily-form').reset(); $('record-id').value=''; $('entry-date').value=$('dashboard-date').value||today(); $('frt-misses').value='0';$('total-chats').value='0';$('verified-orders').value='0';$('actual-hours').value='0';$('required-hours').value=state.agents.find(a=>a.id===$('entry-agent').value)?.requiredHours??8;$('adherence-count').value='0';$('lop-reason').value='';setMessage('form-message',''); updateAttendanceFields(); updateMetricPreview(); }
  function updateAttendanceFields() { const present=$('attendance').value==='Present'; $('performance-fields').hidden=!present; $('lop-reason-wrap').hidden=$('attendance').value!=='LOP'; if(!present) $('metric-preview').innerHTML=''; else updateMetricPreview(); }
  function recordFromForm() { const attendance=$('attendance').value; const old=state.records.find(r=>r.id===$('record-id').value); return { id:old?.id||uid(), agentId:$('entry-agent').value, date:$('entry-date').value, attendance, frtMisses:attendance==='Present'?num('frt-misses'):0,totalChats:attendance==='Present'?num('total-chats'):0,verifiedOrders:attendance==='Present'?num('verified-orders'):0,actualHours:attendance==='Present'?num('actual-hours'):0,requiredHours:attendance==='Present'?num('required-hours'):0,aht:attendance==='Present'&&$('aht').value!==''?num('aht'):null,adherenceMisses:attendance==='Present'?num('adherence-count'):0,notes:attendance==='Present'?$('daily-notes').value.trim():'',lopReason:attendance==='LOP'?$('lop-reason').value.trim():'',createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}; }
  function saveDaily(e) { e.preventDefault(); const r=recordFromForm(); if(!r.agentId){setMessage('form-message','Add an active agent before entering records.',true);return;} if(!r.date){setMessage('form-message','Choose a work date.',true);return;} if(r.verifiedOrders>r.totalChats){setMessage('form-message','Verified orders cannot exceed total chats. Please review the values.',true);return;} const dup=state.records.find(x=>x.agentId===r.agentId&&x.date===r.date&&x.id!==r.id); if(dup&&!confirm('A record already exists for this agent and date. Replace it?')) return; const existing=state.records.findIndex(x=>x.id===r.id); if(existing>=0){state.records[existing]=r;audit('daily_record_updated',r.id,`Updated ${r.date} record for ${agentById(r.agentId)?.name||'agent'}`);} else if(dup){r.id=dup.id;r.createdAt=dup.createdAt;state.records[state.records.findIndex(x=>x.id===dup.id)]=r;audit('daily_record_replaced',r.id,`Replaced ${r.date} record`);} else {state.records.push(r);audit('daily_record_created',r.id,`Created ${r.date} record`);} persist(); setMessage('form-message','Record saved successfully.'); renderAll(); renderDateRecords(); toast('Daily record saved'); $('record-id').value=r.id; }
  function editRecord(id) { const r=state.records.find(x=>x.id===id); if(!r)return; $('entry-date').value=r.date;$('record-id').value=r.id;$('entry-agent').value=r.agentId;$('attendance').value=r.attendance;$('frt-misses').value=r.frtMisses??0;$('total-chats').value=r.totalChats??0;$('verified-orders').value=r.verifiedOrders??0;$('actual-hours').value=r.actualHours??0;$('required-hours').value=r.requiredHours??8;$('aht').value=r.aht??'';$('adherence-count').value=r.adherenceMisses??0;$('daily-notes').value=r.notes||'';$('lop-reason').value=r.lopReason||'';updateAttendanceFields();go('daily');window.scrollTo({top:0,behavior:'smooth'}); }
  function deleteRecord(id) { if(!confirm('Delete this daily record? This cannot be undone unless you have a backup.'))return;state.records=state.records.filter(r=>r.id!==id);audit('daily_record_deleted',id,'Deleted daily record');persist();renderAll();toast('Record deleted'); }
  function renderDateRecords() { const date=$('entry-date').value||today(); const rs=state.records.filter(r=>r.date===date).sort((a,b)=>(agentById(a.agentId)?.name||'').localeCompare(agentById(b.agentId)?.name||'')); $('date-record-count').textContent=`${rs.length} record${rs.length===1?'':'s'}`; $('date-records-table').innerHTML=table(['Agent','Attendance','CVR','FRT','Flags','Actions'],rs.map(r=>`<tr><td>${agentCell(agentById(r.agentId))}</td><td>${statusBadge(r.attendance)}</td><td>${presentRecord(r)&&cvr(r)!==null?badge(`${fmt(cvr(r))}%`,cvr(r)<state.settings.cvrTarget?'red':'green'):'—'}</td><td>${presentRecord(r)?fmt(r.frtMisses,0):'—'}</td><td>${presentRecord(r)?(flags(r).length?badge(flags(r).length,'red'):badge('No flags','green')):'—'}</td><td><button class="table-action" data-edit-record="${esc(r.id)}">Edit</button><button class="table-action danger-text" data-delete-record="${esc(r.id)}">Delete</button></td></tr>`),'No records saved for this date.'); }
  function filteredRecords() { const from=$('filter-from').value,to=$('filter-to').value,agent=$('filter-agent').value,status=$('filter-status').value; return state.records.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to)&&(!agent||r.agentId===agent)&&(!status||r.attendance===status)).sort((a,b)=>b.date.localeCompare(a.date)||(agentById(a.agentId)?.name||'').localeCompare(agentById(b.agentId)?.name||'')); }
  function renderHistory() { const rs=filteredRecords(); $('history-summary').textContent=`${rs.length} record${rs.length===1?'':'s'} match the selected filters`; $('history-table').innerHTML=table(['Date','Agent','Attendance','CVR','FRT misses','Adherence','Login hours','AHT','Flags','Actions'],rs.map(r=>`<tr><td>${dateText(r.date)}</td><td>${agentCell(agentById(r.agentId))}</td><td>${statusBadge(r.attendance)}</td><td>${presentRecord(r)&&cvr(r)!==null?badge(`${fmt(cvr(r))}%`,cvr(r)<state.settings.cvrTarget?'red':'green'):'—'}</td><td>${presentRecord(r)?fmt(r.frtMisses,0):'—'}</td><td>${presentRecord(r)?fmt(r.adherenceMisses,0):'—'}</td><td>${presentRecord(r)?`${fmt(r.actualHours,2)} / ${fmt(r.requiredHours,2)}h`:'—'}</td><td>${presentRecord(r)&&r.aht!==null?`${fmt(r.aht)}m`:'—'}</td><td>${presentRecord(r)&&flags(r).length?badge(flags(r).length,'red'):presentRecord(r)?badge('0','green'):'—'}</td><td><button class="table-action" data-edit-record="${esc(r.id)}">Edit</button></td></tr>`));
    const byAgent=new Map(); rs.forEach(r=>{if(!byAgent.has(r.agentId))byAgent.set(r.agentId,{agent:agentById(r.agentId),records:[]});byAgent.get(r.agentId).records.push(r);}); const rows=[...byAgent.values()].sort((a,b)=>(a.agent?.name||'').localeCompare(b.agent?.name||'')).map(x=>{const eligible=x.records.filter(presentRecord);const f=eligible.reduce((n,r)=>n+totalMisses(r),0);const frt=eligible.reduce((n,r)=>n+Number(r.frtMisses||0),0);const under=eligible.filter(r=>cvr(r)!==null&&cvr(r)<state.settings.cvrTarget).length;const lop=x.records.filter(r=>r.attendance==='LOP').length;return `<tr><td>${agentCell(x.agent)}</td><td>${x.records.length}</td><td>${eligible.length}</td><td>${frt}</td><td>${under}${eligible.length?` / ${eligible.length}`:''}</td><td>${f}</td><td>${lop}</td></tr>`;}); $('agent-summary-table').innerHTML=table(['Agent','Records','Present days','FRT misses','Below CVR target','Flagged categories','LOP days'],rows,'No agent records match these filters.'); }
  function renderAgents() { $('agents-table').innerHTML=table(['Agent','Shift','Required hours','Weekly off','Status','Actions'],state.agents.slice().sort((a,b)=>Number(b.active)-Number(a.active)||(a.name||'').localeCompare(b.name||'')).map(a=>`<tr><td>${agentCell(a)}</td><td>${esc(a.shift||'—')}</td><td>${fmt(a.requiredHours,2)}h</td><td>${esc(a.weeklyOff==='variable'?'Variable':['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(a.weeklyOff)]||'—')}</td><td>${a.active?badge('Active','green'):badge('Inactive','gray')}</td><td><button class="table-action" data-edit-agent="${esc(a.id)}">Edit</button><button class="table-action" data-toggle-agent="${esc(a.id)}">${a.active?'Deactivate':'Activate'}</button></td></tr>`),'No agents added yet. Add your team members above.'); }
  function resetAgentForm() { $('agent-form').reset();$('agent-edit-id').value='';$('agent-active').checked=true;$('agent-required-hours').value='8';setMessage('agent-message',''); }
  function saveAgent(e) { e.preventDefault(); const id=$('agent-edit-id').value; const employeeId=$('employee-id').value.trim();const name=$('agent-name').value.trim(); if(!employeeId||!name)return; if(state.agents.some(a=>a.employeeId.toLowerCase()===employeeId.toLowerCase()&&a.id!==id)){setMessage('agent-message','That employee ID already exists.',true);return;}const old=state.agents.find(a=>a.id===id);const a={id:id||uid(),employeeId,name,shift:$('agent-shift').value.trim(),requiredHours:num('agent-required-hours',8),weeklyOff:$('weekly-off').value,active:$('agent-active').checked,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(old){state.agents[state.agents.findIndex(x=>x.id===id)]=a;audit('agent_updated',id,`Updated agent ${name}`);}else{state.agents.push(a);audit('agent_created',a.id,`Added agent ${name}`);}persist();resetAgentForm();renderAll();toast('Agent saved'); }
  function editAgent(id) {const a=agentById(id);if(!a)return;$('agent-edit-id').value=a.id;$('employee-id').value=a.employeeId;$('agent-name').value=a.name;$('agent-shift').value=a.shift||'';$('agent-required-hours').value=a.requiredHours??8;$('weekly-off').value=a.weeklyOff??'0';$('agent-active').checked=!!a.active;setMessage('agent-message',`Editing ${a.name}`);window.scrollTo({top:0,behavior:'smooth'});}
  function toggleAgent(id) {const a=agentById(id);if(!a)return;a.active=!a.active;a.updatedAt=new Date().toISOString();audit(a.active?'agent_activated':'agent_deactivated',id,`${a.active?'Activated':'Deactivated'} ${a.name}`);persist();renderAll();toast(a.active?'Agent activated':'Agent deactivated');}
  function renderActions() {const filter=$('action-filter-status').value;const list=state.actions.filter(a=>!filter||a.status===filter).sort((a,b)=>(b.actionDate||'').localeCompare(a.actionDate||''));$('actions-table').innerHTML=table(['Date','Agent','Category','Action','Follow-up','Status','Notes','Actions'],list.map(a=>`<tr><td>${dateText(a.actionDate)}</td><td>${agentCell(agentById(a.agentId))}</td><td>${badge(a.category,'blue')}</td><td>${esc(a.actionType)}</td><td>${dateText(a.followUpDate)}</td><td>${badge(a.status,a.status==='Resolved'?'green':a.status==='In Progress'?'blue':'amber')}</td><td class="notes-cell">${esc(a.description.length>75?a.description.slice(0,72)+'…':a.description)}</td><td><button class="table-action" data-edit-action="${esc(a.id)}">Edit</button><button class="table-action danger-text" data-delete-action="${esc(a.id)}">Delete</button></td></tr>`),'No coaching or action records yet.');}
  function clearActionForm(){ $('action-form').reset();$('action-edit-id').value='';$('action-date').value=today();$('action-status').value='Open';setMessage('action-message',''); }
  function saveAction(e){e.preventDefault();const id=$('action-edit-id').value;const old=state.actions.find(a=>a.id===id);const a={id:id||uid(),agentId:$('action-agent').value,actionDate:$('action-date').value,category:$('action-category').value,actionType:$('action-type').value,status:$('action-status').value,followUpDate:$('follow-up-date').value,description:$('action-description').value.trim(),owner:$('action-owner').value.trim(),evidence:$('action-evidence').value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!a.agentId){setMessage('action-message','Add an active agent first.',true);return;}if(old){state.actions[state.actions.findIndex(x=>x.id===id)]=a;audit('action_updated',id,'Updated coaching/action record');}else{state.actions.push(a);audit('action_created',a.id,'Created coaching/action record');}persist();clearActionForm();renderActions();toast('Action saved');}
  function editAction(id){const a=state.actions.find(x=>x.id===id);if(!a)return;$('action-edit-id').value=a.id;$('action-agent').value=a.agentId;$('action-date').value=a.actionDate;$('action-category').value=a.category;$('action-type').value=a.actionType;$('action-status').value=a.status;$('follow-up-date').value=a.followUpDate||'';$('action-description').value=a.description;$('action-owner').value=a.owner||'';$('action-evidence').value=a.evidence||'';setMessage('action-message',`Editing action for ${agentById(a.agentId)?.name||'agent'}`);window.scrollTo({top:0,behavior:'smooth'});}
  function deleteAction(id){if(!confirm('Delete this action record?'))return;state.actions=state.actions.filter(a=>a.id!==id);audit('action_deleted',id,'Deleted coaching/action record');persist();renderActions();toast('Action deleted');}
  function loadSettingsForm(){const s=state.settings;$('setting-cvr').value=s.cvrTarget;$('setting-frt').value=s.frtThreshold??'';$('setting-aht').value=s.ahtThreshold??'';$('setting-tolerance').value=s.loginTolerance;$('setting-repeat').value=s.repeatThreshold;}
  function saveSettings(e){e.preventDefault();const old={...state.settings};const frt=$('setting-frt').value.trim(),aht=$('setting-aht').value.trim();state.settings={cvrTarget:num('setting-cvr',30),frtThreshold:frt===''?null:num('setting-frt'),ahtThreshold:aht===''?null:num('setting-aht'),loginTolerance:num('setting-tolerance'),repeatThreshold:num('setting-repeat',3)};audit('settings_updated','settings',`Changed settings from ${JSON.stringify(old)} to ${JSON.stringify(state.settings)}`);persist();renderAll();setMessage('settings-message','Settings saved. Dashboard flags have been recalculated.');toast('Settings saved');}
  function exportJson(){download(`agent-tracker-backup-${today()}.json`,JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json');}
  function exportCsv(rs=state.records,name=`agent-tracker-records-${today()}.csv`){download(name,'\ufeff'+recordsCsv(rs),'text/csv;charset=utf-8;');}
  async function importJson(e){const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!parsed||!Array.isArray(parsed.agents)||!Array.isArray(parsed.records)||!Array.isArray(parsed.actions)||!parsed.settings)throw new Error('This does not look like a valid Agent Tracker backup.');if(!confirm('Restore this backup? It will replace all current data in this browser. Export a backup first if needed.'))return;state={...defaultState(),...parsed,settings:{...defaultState().settings,...parsed.settings},audit:Array.isArray(parsed.audit)?parsed.audit:[]};persist();renderAll();loadSettingsForm();toast('Backup restored successfully');}catch(err){toast(err.message||'Could not read this backup.');}finally{e.target.value='';}}
  function resetData(){if(!confirm('Delete ALL agents, daily records, actions, and settings from this browser?'))return;if(!confirm('Final confirmation: this cannot be undone without a JSON backup. Continue?'))return;state=defaultState();persist();renderAll();loadSettingsForm();resetDailyForm();resetAgentForm();clearActionForm();toast('Local data reset');}
  function addDemoAgents(){if(state.agents.length&&!confirm('Add three sample agents to the existing roster?'))return;const samples=[['DEMO001','Sample Agent One','6 AM–3 PM',8,'0'],['DEMO002','Sample Agent Two','6 AM–3 PM',8,'1'],['DEMO003','Sample Agent Three','2 PM–11 PM',8,'2']];samples.forEach(([employeeId,name,shift,requiredHours,weeklyOff])=>{if(!state.agents.some(a=>a.employeeId===employeeId))state.agents.push({id:uid(),employeeId,name,shift,requiredHours,weeklyOff,active:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),demo:true});});audit('demo_agents_added','agents','Added sample agent records');persist();renderAll();toast('Sample agents added. You can edit or deactivate them.');}
  function renderAll(){fillAgentSelects();renderDashboard();renderDateRecords();renderHistory();renderAgents();renderActions();}
  document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
  $('quick-entry').addEventListener('click',()=>go('daily'));
  $('dashboard-date').value=today();$('entry-date').value=today();$('action-date').value=today();$('today-label').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'});
  $('dashboard-date').addEventListener('change',renderDashboard);$('entry-date').addEventListener('change',renderDateRecords);
  $('attendance').addEventListener('change',updateAttendanceFields);['frt-misses','total-chats','verified-orders','actual-hours','required-hours','aht','adherence-count'].forEach(id=>$(id).addEventListener('input',updateMetricPreview));
  $('entry-agent').addEventListener('change',()=>{if(!$('record-id').value){const a=agentById($('entry-agent').value);if(a)$('required-hours').value=a.requiredHours??8;updateMetricPreview();}});
  $('daily-form').addEventListener('submit',saveDaily);$('reset-form').addEventListener('click',resetDailyForm);
  ['filter-from','filter-to','filter-agent','filter-status'].forEach(id=>$(id).addEventListener('change',renderHistory));$('export-filtered').addEventListener('click',()=>exportCsv(filteredRecords(),`agent-tracker-filtered-${today()}.csv`));
  $('agent-form').addEventListener('submit',saveAgent);$('cancel-agent-edit').addEventListener('click',resetAgentForm);$('add-demo-agents').addEventListener('click',addDemoAgents);
  $('action-form').addEventListener('submit',saveAction);$('clear-action').addEventListener('click',clearActionForm);$('action-filter-status').addEventListener('change',renderActions);
  $('settings-form').addEventListener('submit',saveSettings);$('github-load').addEventListener('click',()=>connectGitHub('load'));$('github-upload').addEventListener('click',()=>connectGitHub('upload'));$('github-disconnect').addEventListener('click',disconnectGitHub);$('export-json').addEventListener('click',exportJson);$('export-csv').addEventListener('click',()=>exportCsv());$('import-json').addEventListener('change',importJson);$('reset-data').addEventListener('click',resetData);
  document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editRecord)editRecord(b.dataset.editRecord);if(b.dataset.deleteRecord)deleteRecord(b.dataset.deleteRecord);if(b.dataset.editAgent)editAgent(b.dataset.editAgent);if(b.dataset.toggleAgent)toggleAgent(b.dataset.toggleAgent);if(b.dataset.editAction)editAction(b.dataset.editAction);if(b.dataset.deleteAction)deleteAction(b.dataset.deleteAction);});
  // Make a weekly-off default visible as a schedule hint, but do not infer attendance for missing records.
  $('entry-agent').addEventListener('change',()=>{const a=agentById($('entry-agent').value);if(!a)return;const dow=new Date(`${$('entry-date').value||today()}T12:00:00`).getDay();if(a.weeklyOff!=='variable'&&Number(a.weeklyOff)===dow&&!state.records.some(r=>r.agentId===a.id&&r.date===$('entry-date').value)){ $('attendance').value='Weekly Off';updateAttendanceFields();}});
  initGitHubSettings();renderAll();loadSettingsForm();updateAttendanceFields();
})();
